### ISSUE TITLE
Unable to find the package in Package Control

### ISSUE THREAD

**Issue by agemooij** [gwenzek/scalaSublimeSyntax#1]
I can find this package on the Package Control website but neither me or my colleague could find it using Package Control inside ST3. I've deleted my PC cache, reinstalled PC, reloaded the list of packages multiple times but it never ever shows up when looking for "Scala Syntax" or even "Scala" or other permutations of the name.

Any idea what could be causing this?

**Comment by gwenzek** [comment]
Hi,
The most probable problem is that this plugins needs build >3084 of Sublime.
I think Package control hide it from you if you don't have a build recent enough.
For now build 3084 is still a dev build, and is reserved to registered users.
I hope Jon will soon release a new public build.

Which build of sublime are you using ?

**Comment by agemooij** [comment]
I'm using 3084, so that makes sense. I thought I was on development builds but I recently migrated toa new machine and it looks like I'm now on stable. I'll upgrade and try again. 

It might be good to mention this in your README.

**Comment by agemooij** [comment]
OK, PC can now find it and install it. Thanks!

**Comment by gwenzek** [comment]
Great, as the plugin is quite new I'm interested in any feedback. Feel free
to open more issues if you have other problems/questions/requests.
